#!/usr/bin/env python3
'''Module to list all the databases in mongodb
'''

from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient()

# List all databases
for db in client.list_databases():
    print(db)
